import type {ProposalData} from "../components/proposal-context.tsx";
import {rooms,type Room} from "../data/rooms.ts";
import {moneyToRubles} from "./proposal-money.ts";
import type {ProposalVersionResponse} from "./proposal-version.ts";
import type {RefinanceCalculation} from "./refinance-types.ts";
const rub=(value:unknown)=>typeof value==="number"?(moneyToRubles(value as never)??0):0;
const rubNullable=(value:unknown)=>value===null||value===undefined?null:rub(value);
function mapRefinance(value:unknown):RefinanceCalculation|undefined{if(!value||typeof value!=="object")return undefined;const row=value as Record<string,unknown>;if(row.enabled!==true)return undefined;return{enabled:true,refinanceAfterMonths:Number(row.refinanceAfterMonths??0),refinanceDate:typeof row.refinanceDate==="string"?row.refinanceDate:null,assumedAnnualRate:Number(row.assumedAnnualRate??0),outstandingPrincipal:rubNullable(row.outstandingPrincipal),remainingTermMonths:Number(row.remainingTermMonths??0),paymentBeforeRefinance:rubNullable(row.paymentBeforeRefinance),paymentAfterRefinance:rubNullable(row.paymentAfterRefinance),isValid:row.isValid!==false,validationMessages:Array.isArray(row.validationMessages)?row.validationMessages.map(String):[]}}
function snapshotRoom(value:ProposalVersionResponse["data"]):Room{const asset=rooms.find(item=>item.roomNumber.replace(/^№/,"")===value.unitSnapshot.unitNumber.replace(/^№/,""));return{roomNumber:value.unitSnapshot.unitNumber,floor:value.unitSnapshot.floor,area:value.unitSnapshot.area??0,price:value.unitSnapshot.price,pricePerSqm:value.unitSnapshot.pricePerSqm??0,layoutId:asset?.layoutId??"",renderSetId:asset?.renderSetId??""}}
export function mapProposalVersion(value:ProposalVersionResponse["data"]):ProposalData{
  const base={room:snapshotRoom(value),investment:value.investmentProjection},p=value.purchaseProjection;
  if(!p)return{...base,financingType:"none"};
  if(value.purchaseType==="INSTALLMENT"){
    const rows=Array.isArray(p.schedule)?p.schedule as Array<Record<string,unknown>>:[];
    let afterTopUp=false;
    const schedule=rows.map((item,index)=>{const type=item.type==="DOWN_PAYMENT"?"initial" as const:item.type==="INTERMEDIATE"?"top-up" as const:item.type==="FINAL"?"final" as const:afterTopUp?"regular-second" as const:"regular-first" as const;if(type==="top-up")afterTopUp=true;return{id:String(item.id??index),date:String(item.date??""),type,label:String(item.label??""),amount:rub(item.amount),cumulativeAmount:rub(item.cumulativeAmount)}});
    return{...base,financingType:"installment",installment:{listPrice:rub(p.purchasePrice),discountPercent:Number(p.discountPercent??0),discountAmount:rub(p.discountAmount),discountedPrice:rub(p.discountedPrice),initialPaymentPercent:Number(p.downPaymentPercent??0),initialPayment:rub(p.downPayment),monthlyPayment:rub(p.monthlyPayment),firstPeriodPaymentCount:schedule.filter(item=>item.type==="regular-first").length,paymentsBeforeTopUp:schedule.filter(item=>item.type==="regular-first").reduce((sum,item)=>sum+item.amount,0),topUpPayment:rub(p.keyTopUpPayment),targetEscrow:rub(p.requiredEscrowAmount),secondPeriodPaymentCount:schedule.filter(item=>item.type==="regular-second").length,secondPeriodPayments:schedule.filter(item=>item.type==="regular-second").reduce((sum,item)=>sum+item.amount,0),finalPayment:rub(p.finalPayment)},schedule};
  }
  const basePrice=rub(p.basePrice??p.purchasePrice),price=rub(p.dealPrice??p.purchasePrice),down=rub(p.downPaymentAmount??p.downPayment),loan=rub(p.loanPrincipal??p.loanAmount),termMonths=Number(p.termMonths??p.loanTermMonths??0),legacyStages=Array.isArray(p.stages)?p.stages as Array<Record<string,unknown>>:[],canonicalTranches=Array.isArray(p.tranches)?p.tranches as Array<Record<string,unknown>>:[];
  const stages=(canonicalTranches.length?canonicalTranches:legacyStages).map((item,index)=>{const legacy=legacyStages[index]??{},issueDate=String(item.date??item.issueDate??legacy.issueDate??"");return{trancheId:String(legacy.trancheId??`tranche-${index+1}`),trancheNumber:Number(item.index??item.trancheNumber??legacy.trancheNumber??index+1),trancheAmount:rub(item.amount??item.trancheAmount??legacy.trancheAmount),issueMonth:0,issueDate,startPaymentMonth:1,endPaymentMonth:Number(legacy.paymentCount??0),paymentCount:Number(legacy.paymentCount??0),outstandingAfterIssue:rub(legacy.outstandingAfterIssue),remainingTermMonths:termMonths,monthlyPayment:rub(item.paymentAfterTranche??item.monthlyPayment??legacy.monthlyPayment),balanceBeforeNextTranche:rub(legacy.balanceBeforeNextTranche)}});
  return{...base,financingType:"mortgage",mortgageKind:value.purchaseType==="MORTGAGE"?"standard":"tranche",standardMonthlyPayment:rub(p.monthlyPayment),refinance:mapRefinance(p.refinance),mortgage:{basePrice,discountPercent:Number(p.discountPercent??0),discountAmount:rub(p.discountAmount),price,initialPayment:down,initialPaymentPercent:Number(p.downPaymentPercent??(price?down/price*100:0)),loanAmount:loan,annualRate:Number(p.annualRate??p.annualRatePercent??0),termMonths,termYears:termMonths/12,trancheTotal:rub(p.trancheTotal??p.loanPrincipal??p.loanAmount),difference:rub(p.difference),isBalanced:!Array.isArray(p.validationMessages)||p.validationMessages.length===0,validationMessages:Array.isArray(p.validationMessages)?p.validationMessages.map(String):[],stages,schedule:[],remainingBalance:rub(p.remainingBalance),totalInterest:rub(p.totalInterest??p.overpayment),totalPayments:rub(p.totalPayments??p.totalPayment)}};
}
