import type {ProposalData} from "../components/proposal-context.tsx";
import {rooms,type Room} from "../data/rooms.ts";
import {moneyToRubles} from "./proposal-money.ts";
import type {ProposalVersionResponse} from "./proposal-version.ts";
const rub=(value:unknown)=>typeof value==="number"?(moneyToRubles(value as never)??0):0;
function snapshotRoom(value:ProposalVersionResponse["data"]):Room{const asset=rooms.find(item=>item.roomNumber.replace(/^№/,"")===value.unitSnapshot.unitNumber.replace(/^№/,""));return{roomNumber:value.unitSnapshot.unitNumber,floor:value.unitSnapshot.floor,area:value.unitSnapshot.area??0,price:value.unitSnapshot.price,pricePerSqm:value.unitSnapshot.pricePerSqm??0,layoutId:asset?.layoutId??"",renderSetId:asset?.renderSetId??""}}
export function mapProposalVersion(value:ProposalVersionResponse["data"]):ProposalData{
  const base={room:snapshotRoom(value),investment:value.investmentProjection},p=value.purchaseProjection;
  if(!p)return{...base,financingType:"none"};
  if(value.purchaseType==="INSTALLMENT"){
    const rows=Array.isArray(p.schedule)?p.schedule as Array<Record<string,unknown>>:[];
    let afterTopUp=false;
    const schedule=rows.map((item,index)=>{const type=item.type==="DOWN_PAYMENT"?"initial" as const:item.type==="INTERMEDIATE"?"top-up" as const:item.type==="FINAL"?"final" as const:afterTopUp?"regular-second" as const:"regular-first" as const;if(type==="top-up")afterTopUp=true;return{id:String(item.id??index),date:String(item.date??""),type,label:String(item.label??""),amount:rub(item.amount),cumulativeAmount:rub(item.cumulativeAmount)}});
    return{...base,financingType:"installment",installment:{listPrice:rub(p.purchasePrice),discountPercent:Number(p.discountPercent??0),discountAmount:rub(p.discountAmount),discountedPrice:rub(p.discountedPrice),initialPaymentPercent:Number(p.downPaymentPercent??0),initialPayment:rub(p.downPayment),monthlyPayment:rub(p.monthlyPayment),firstPeriodPaymentCount:schedule.filter(item=>item.type==="regular-first").length,paymentsBeforeTopUp:schedule.filter(item=>item.type==="regular-first").reduce((sum,item)=>sum+item.amount,0),topUpPayment:rub(p.keyTopUpPayment),targetEscrow:rub(p.requiredEscrowAmount),secondPeriodPaymentCount:schedule.filter(item=>item.type==="regular-second").length,secondPeriodPayments:schedule.filter(item=>item.type==="regular-second").reduce((sum,item)=>sum+item.amount,0),finalPayment:rub(p.finalPayment)},schedule};
  }
  const price=rub(p.purchasePrice),down=rub(p.downPayment),stages=Array.isArray(p.stages)?p.stages as Array<Record<string,unknown>>:[];
  return{...base,financingType:"mortgage",mortgageKind:value.purchaseType==="MORTGAGE"?"standard":"tranche",standardMonthlyPayment:rub(p.monthlyPayment),mortgage:{basePrice:price,discountPercent:0,discountAmount:0,price,initialPayment:down,initialPaymentPercent:price?down/price*100:0,loanAmount:rub(p.loanAmount),annualRate:Number(p.annualRatePercent??0),termMonths:Number(p.loanTermMonths??0),termYears:Number(p.loanTermMonths??0)/12,trancheTotal:rub(p.trancheTotal??p.loanAmount),difference:rub(p.difference),isBalanced:!Array.isArray(p.validationMessages)||p.validationMessages.length===0,validationMessages:Array.isArray(p.validationMessages)?p.validationMessages.map(String):[],stages:stages.map((item,index)=>({trancheId:String(item.trancheId??index),trancheNumber:Number(item.trancheNumber??index+1),trancheAmount:rub(item.trancheAmount),issueMonth:0,issueDate:String(item.issueDate??""),startPaymentMonth:1,endPaymentMonth:Number(item.paymentCount??0),paymentCount:Number(item.paymentCount??0),outstandingAfterIssue:rub(item.outstandingAfterIssue),remainingTermMonths:Number(p.loanTermMonths??0),monthlyPayment:rub(item.monthlyPayment),balanceBeforeNextTranche:rub(item.balanceBeforeNextTranche)})),schedule:[],remainingBalance:rub(p.remainingBalance),totalInterest:rub(p.totalInterest??p.overpayment),totalPayments:rub(p.totalPayments??p.totalPayment)}};
}
