import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { mapProposalVersion } from "./map-proposal-version.ts";
import { parseProposalVersion, type ProposalVersionResponse } from "./proposal-version.ts";

const base: ProposalVersionResponse = { data: { id: "11111111-1111-4111-8111-111111111111", schemaVersion: 1, sellSessionId: "22222222-2222-4222-8222-222222222222", unitId: "CBS-B1-704", returnUrl: "http://localhost:3001/inventory/cosmos-black-sea/unit/CBS-B1-704", unitSnapshot: { unitId: "CBS-B1-704", unitNumber: "704", floor: 7, area: 38, price: 22_990_000, pricePerSqm: 605_000, status: "AVAILABLE", viewType: "SEA", capturedAt: "2026-08-13T00:00:00.000Z" }, purchaseScenarioRef: null, purchaseProjection: null, purchaseType: null, investmentCaseRef: null, investmentProjection: null, clientContext: null, salespersonContext: null, presentationConfig: {}, createdAt: "2026-08-13T00:00:00.000Z" }, liveCheck: { priceChanged: false, statusChanged: false, currentPrice: 22_990_000, currentStatus: "AVAILABLE" } };

test("parses sanitized version and maps Unit-only without calculators", () => { const parsed = parseProposalVersion(base); assert.equal(mapProposalVersion(parsed.data).financingType, "none"); });
test("maps purchase and investment projections verbatim", () => { const value = structuredClone(base); value.data.purchaseType = "MORTGAGE"; value.data.purchaseScenarioRef = "p"; value.data.purchaseProjection = { purchasePrice: 2_299_000_000, downPayment: 689_700_000, loanAmount: 1_609_300_000, annualRatePercent: "19.2", loanTermMonths: 360, monthlyPayment: 24_253_500, totalPayment: 8_731_260_000, overpayment: 7_121_960_000, validationMessages: [] }; value.data.investmentCaseRef = "i"; value.data.investmentProjection = { firstYearIncome: 1_200_000, firstYearYield: 5.2, horizonYears: 10 }; const mapped = mapProposalVersion(value.data); assert.equal(mapped.financingType, "mortgage"); assert.equal(mapped.investment?.firstYearIncome, 1_200_000); if (mapped.financingType === "mortgage") assert.equal(mapped.standardMonthlyPayment, 242_535); });
test("maps installment and tranche projections without recalculation", () => { const installment = structuredClone(base); installment.data.purchaseType = "INSTALLMENT"; installment.data.purchaseProjection = { purchasePrice: 2_299_000_000, discountedPrice: 2_200_000_000, downPayment: 440_000_000, downPaymentPercent: 20, monthlyPayment: 10_000_000, schedule: [{ id: "1", date: "2026-09-01", type: "INTERMEDIATE", label: "Top up", amount: 50_000_000, cumulativeAmount: 490_000_000 }] }; const i = mapProposalVersion(installment.data); assert.equal(i.financingType, "installment"); if (i.financingType === "installment") assert.equal(i.installment.monthlyPayment, 100_000); const tranche = structuredClone(base); tranche.data.purchaseType = "TRANCHE_MORTGAGE"; tranche.data.purchaseProjection = { purchasePrice: 2_299_000_000, downPayment: 689_700_000, loanAmount: 1_609_300_000, annualRatePercent: "19.2", loanTermMonths: 360, stages: [{ trancheId: "t1", trancheNumber: 1, trancheAmount: 800_000_000, monthlyPayment: 12_000_000, paymentCount: 12 }] }; const t = mapProposalVersion(tranche.data); assert.equal(t.financingType, "mortgage"); if (t.financingType === "mortgage") assert.equal(t.mortgageKind, "tranche"); });
test("preserves installment periods from the authoritative schedule",()=>{const value=structuredClone(base);value.data.purchaseType="INSTALLMENT";value.data.purchaseProjection={purchasePrice:2_299_000_000,discountedPrice:2_253_020_000,discountAmount:45_980_000,downPayment:450_604_000,downPaymentPercent:"20",monthlyPayment:10_000_000,keyTopUpPayment:575_906_000,finalPayment:1_016_510_000,schedule:[{id:"a",type:"MONTHLY",amount:10_000_000},{id:"top",type:"INTERMEDIATE",amount:575_906_000},{id:"b",type:"MONTHLY",amount:10_000_000}]};const mapped=mapProposalVersion(value.data);assert.equal(mapped.financingType,"installment");if(mapped.financingType==="installment"){assert.equal(mapped.installment.firstPeriodPaymentCount,1);assert.equal(mapped.installment.secondPeriodPaymentCount,1);assert.equal(mapped.installment.secondPeriodPayments,100_000)}});
test("mapper has no calculation-engine dependency", () => { const source = readFileSync(new URL("./map-proposal-version.ts", import.meta.url), "utf8"); assert.doesNotMatch(source, /calculate|engine|payment-calculator|investment-calculator/i); });
test("rejects internal or malformed payload shape", () => { assert.throws(() => parseProposalVersion({ ...base, data: { ...base.data, investmentProjection: [] } }), /INVALID_PROPOSAL_VERSION/); assert.throws(() => parseProposalVersion({ ...base, data: { ...base.data, schemaVersion: 99 } }), /UNSUPPORTED_PROPOSAL_VERSION/); });
test("rejects a ProposalVersion that has refs without matching projections",()=>{assert.throws(()=>parseProposalVersion({...base,data:{...base.data,purchaseScenarioRef:"p",purchaseType:"MORTGAGE",purchaseProjection:null}}),/INVALID_PROPOSAL_COMPOSITION/);assert.throws(()=>parseProposalVersion({...base,data:{...base.data,investmentCaseRef:"i",investmentProjection:null}}),/INVALID_PROPOSAL_COMPOSITION/)});
test("maps optional refinance snapshot and keeps older versions backward compatible",()=>{const legacy=structuredClone(base);legacy.data.purchaseType="TRANCHE_MORTGAGE";legacy.data.purchaseScenarioRef="p";legacy.data.purchaseProjection={purchasePrice:2_299_000_000,downPayment:689_700_000,loanAmount:1_609_300_000,annualRatePercent:"19.2",loanTermMonths:360,stages:[]};const oldMapped=mapProposalVersion(parseProposalVersion(legacy).data);assert.equal(oldMapped.financingType,"mortgage");if(oldMapped.financingType!=="mortgage")assert.fail("Expected mortgage");assert.equal(oldMapped.refinance,undefined);const current=structuredClone(legacy);if(!current.data.purchaseProjection)assert.fail("Expected projection");current.data.purchaseProjection.refinance={enabled:true,refinanceAfterMonths:24,refinanceDate:"2028-08-15",assumedAnnualRate:10,outstandingPrincipal:1_394_000_000,remainingTermMonths:336,paymentBeforeRefinance:6_490_100,paymentAfterRefinance:12_450_000,isValid:true,validationMessages:[]};const mapped=mapProposalVersion(parseProposalVersion(current).data);assert.equal(mapped.financingType,"mortgage");if(mapped.financingType!=="mortgage")assert.fail("Expected mortgage");assert.equal(mapped.refinance?.outstandingPrincipal,13_940_000);assert.equal(mapped.refinance?.paymentAfterRefinance,124_500);assert.equal(mapped.refinance?.refinanceDate,"2028-08-15")});
test("maps canonical v2 pricing, actual tranches, refinance and investment without recalculation",()=>{const value=structuredClone(base);value.data.purchaseScenarioRef="p-v2";value.data.purchaseType="TRANCHE_MORTGAGE";value.data.purchaseProjection={purchasePrice:2_230_030_000,downPayment:669_009_000,loanAmount:1_561_021_000,annualRatePercent:"19.2",loanTermMonths:360,trancheTotal:1_561_021_000,difference:0,validationMessages:[],basePrice:2_299_000_000,discountPercent:"3",discountAmount:68_970_000,dealPrice:2_230_030_000,downPaymentPercent:"30",downPaymentAmount:669_009_000,annualRate:"19.2",termMonths:360,loanPrincipal:1_561_021_000,tranches:[{index:1,date:"2026-08-15",amount:468_306_300,percentage:"30",paymentAfterTranche:7_636_600},{index:2,date:"2028-08-15",amount:1_092_714_700,percentage:"70",paymentAfterTranche:25_455_300}],stages:[{trancheId:"tranche-1",paymentCount:24},{trancheId:"tranche-2",paymentCount:336}],refinance:{enabled:true,refinanceAfterMonths:24,refinanceDate:"2028-08-15",assumedAnnualRate:"10",outstandingPrincipal:1_557_137_159,remainingTermMonths:336,paymentBeforeRefinance:7_636_600,paymentAfterRefinance:13_826_761}};value.data.investmentCaseRef="i-v2";value.data.investmentProjection={scenarioLabel:"Базовый",firstYearIncome:1_200_000,firstYearYield:5.2,horizonYears:10};const mapped=mapProposalVersion(parseProposalVersion(value).data);assert.equal(mapped.financingType,"mortgage");if(mapped.financingType!=="mortgage")assert.fail("Expected mortgage");assert.deepEqual({basePrice:mapped.mortgage.basePrice,discountPercent:mapped.mortgage.discountPercent,price:mapped.mortgage.price,initialPayment:mapped.mortgage.initialPayment,loan:mapped.mortgage.loanAmount}, {basePrice:22_990_000,discountPercent:3,price:22_300_300,initialPayment:6_690_090,loan:15_610_210});assert.deepEqual(mapped.mortgage.stages.map(stage=>[stage.trancheAmount,stage.monthlyPayment]),[[4_683_063,76_366],[10_927_147,254_553]]);assert.equal(mapped.refinance?.outstandingPrincipal,15_571_371.59);assert.equal(mapped.refinance?.paymentAfterRefinance,138_267.61);assert.equal(mapped.investment?.scenarioLabel,"Базовый")});
test("canonical v2 parser rejects malformed Money while legacy remains accepted",()=>{const legacy=structuredClone(base);legacy.data.purchaseScenarioRef="legacy";legacy.data.purchaseType="TRANCHE_MORTGAGE";legacy.data.purchaseProjection={purchasePrice:2_299_000_000};assert.doesNotThrow(()=>parseProposalVersion(legacy));const broken=structuredClone(legacy);broken.data.purchaseProjection={basePrice:2.5,dealPrice:2};assert.throws(()=>parseProposalVersion(broken),/INVALID_PROPOSAL_VERSION/)});
