import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { mapProposalVersion } from "./map-proposal-version.ts";
import { parseProposalVersion, type ProposalVersionResponse } from "./proposal-version.ts";

const base: ProposalVersionResponse = { data: { id: "11111111-1111-4111-8111-111111111111", schemaVersion: 1, sellSessionId: "22222222-2222-4222-8222-222222222222", unitId: "CBS-B1-704", returnUrl: "http://localhost:3001/inventory/cosmos-black-sea/unit/CBS-B1-704", unitSnapshot: { unitId: "CBS-B1-704", unitNumber: "704", floor: 7, area: 38, price: 22_990_000, pricePerSqm: 605_000, status: "AVAILABLE", viewType: "SEA", capturedAt: "2026-08-13T00:00:00.000Z" }, purchaseScenarioRef: null, purchaseProjection: null, purchaseType: null, investmentCaseRef: null, investmentProjection: null, clientContext: null, salespersonContext: null, presentationConfig: {}, createdAt: "2026-08-13T00:00:00.000Z" }, liveCheck: { priceChanged: false, statusChanged: false, currentPrice: 22_990_000, currentStatus: "AVAILABLE" } };

test("parses sanitized version and maps Unit-only without calculators", () => { const parsed = parseProposalVersion(base); assert.equal(mapProposalVersion(parsed.data).financingType, "none"); });
test("maps purchase and investment projections verbatim", () => { const value = structuredClone(base); value.data.purchaseType = "MORTGAGE"; value.data.purchaseScenarioRef = "p"; value.data.purchaseProjection = { purchasePrice: 2_299_000_000, downPayment: 689_700_000, loanAmount: 1_609_300_000, annualRatePercent: "19.2", loanTermMonths: 360, monthlyPayment: 24_253_500, totalPayment: 8_731_260_000, overpayment: 7_121_960_000, validationMessages: [] }; value.data.investmentCaseRef = "i"; value.data.investmentProjection = { firstYearIncome: 1_200_000, firstYearYield: 5.2, horizonYears: 10 }; const mapped = mapProposalVersion(value.data); assert.equal(mapped.financingType, "mortgage"); assert.equal(mapped.investment?.firstYearIncome, 1_200_000); if (mapped.financingType === "mortgage") assert.equal(mapped.standardMonthlyPayment, 242_535); });
test("maps installment and tranche projections without recalculation", () => { const installment = structuredClone(base); installment.data.purchaseType = "INSTALLMENT"; installment.data.purchaseProjection = { purchasePrice: 2_299_000_000, discountedPrice: 2_200_000_000, downPayment: 440_000_000, downPaymentPercent: 20, monthlyPayment: 10_000_000, schedule: [{ id: "1", date: "2026-09-01", type: "INTERMEDIATE", label: "Top up", amount: 50_000_000, cumulativeAmount: 490_000_000 }] }; const i = mapProposalVersion(installment.data); assert.equal(i.financingType, "installment"); if (i.financingType === "installment") assert.equal(i.installment.monthlyPayment, 100_000); const tranche = structuredClone(base); tranche.data.purchaseType = "TRANCHE_MORTGAGE"; tranche.data.purchaseProjection = { purchasePrice: 2_299_000_000, downPayment: 689_700_000, loanAmount: 1_609_300_000, annualRatePercent: "19.2", loanTermMonths: 360, stages: [{ trancheId: "t1", trancheNumber: 1, trancheAmount: 800_000_000, monthlyPayment: 12_000_000, paymentCount: 12 }] }; const t = mapProposalVersion(tranche.data); assert.equal(t.financingType, "mortgage"); if (t.financingType === "mortgage") assert.equal(t.mortgageKind, "tranche"); });
test("preserves installment periods from the authoritative schedule",()=>{const value=structuredClone(base);value.data.purchaseType="INSTALLMENT";value.data.purchaseProjection={purchasePrice:2_299_000_000,discountedPrice:2_253_020_000,discountAmount:45_980_000,downPayment:450_604_000,downPaymentPercent:"20",monthlyPayment:10_000_000,keyTopUpPayment:575_906_000,finalPayment:1_016_510_000,schedule:[{id:"a",type:"MONTHLY",amount:10_000_000},{id:"top",type:"INTERMEDIATE",amount:575_906_000},{id:"b",type:"MONTHLY",amount:10_000_000}]};const mapped=mapProposalVersion(value.data);assert.equal(mapped.financingType,"installment");if(mapped.financingType==="installment"){assert.equal(mapped.installment.firstPeriodPaymentCount,1);assert.equal(mapped.installment.secondPeriodPaymentCount,1);assert.equal(mapped.installment.secondPeriodPayments,100_000)}});
test("mapper has no calculation-engine dependency", () => { const source = readFileSync(new URL("./map-proposal-version.ts", import.meta.url), "utf8"); assert.doesNotMatch(source, /calculate|engine|payment-calculator|investment-calculator/i); });
test("rejects internal or malformed payload shape", () => { assert.throws(() => parseProposalVersion({ ...base, data: { ...base.data, investmentProjection: [] } }), /INVALID_PROPOSAL_VERSION/); assert.throws(() => parseProposalVersion({ ...base, data: { ...base.data, schemaVersion: 99 } }), /UNSUPPORTED_PROPOSAL_VERSION/); });
