"use client";
import {useEffect,useMemo,useState} from "react";
import {safeInventoryReturnUrl} from "../lib/inventory-return-url";
import {mapProposalVersion} from "../lib/map-proposal-version";
import {formatRubles} from "../lib/proposal-money";
import {parseProposalVersion,type ProposalVersionResponse} from "../lib/proposal-version";
import {ProposalProvider} from "./proposal-context";
import {ProposalPreview} from "./proposal-preview";

function Content({contextId}:{contextId:string}){
 const[value,setValue]=useState<ProposalVersionResponse|null>(null),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();fetch(`/api/proposal-version/${encodeURIComponent(contextId)}`,{signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error(response.status===404?"Предложение не найдено. Вернитесь к продаже и создайте новую версию.":"Не удалось связаться с Inventory. Повторите попытку позже.");return parseProposalVersion(await response.json())}).then(setValue).catch(reason=>{if(!(reason instanceof DOMException&&reason.name==="AbortError"))setError(reason instanceof Error?reason.message:"Не удалось открыть предложение.")});return()=>controller.abort()},[contextId]);
 const proposal=useMemo(()=>value?mapProposalVersion(value.data):null,[value]);
 if(error)return <main className="min-h-screen bg-stone-950 p-5 text-white"><p className="eyebrow">COSMOS BLACK SEA · SALES</p><h1 className="mt-4 font-serif text-4xl">Не удалось открыть КП</h1><p className="mt-4 max-w-xl text-stone-400">{error}</p></main>;
 if(!value||!proposal)return <main className="min-h-screen bg-stone-950 p-5 text-white"><p className="eyebrow">COSMOS BLACK SEA · SALES</p><p className="mt-4">Готовим предложение…</p></main>;
 const{data,liveCheck}=value,unit=data.unitSnapshot,back=safeInventoryReturnUrl(data.returnUrl),investment=data.investmentProjection;
 const purchase=data.purchaseType==="INSTALLMENT"?"Рассрочка":data.purchaseType==="TRANCHE_MORTGAGE"?"Траншевая ипотека":data.purchaseType?"Стандартная ипотека":"Без схемы покупки";
 const metrics:Array<[string,string]>=investment?[["Сценарий",String(investment.scenarioLabel??"—")],["Доход, год 1",formatRubles(Number(investment.firstYearIncome??0))],["Доходность",`${Number(investment.firstYearYield??0).toFixed(1)}%`],["Рост стоимости",formatRubles(Number(investment.capitalGain??0))],["Горизонт",`${String(investment.horizonYears??"—")} лет`]]:[];
 const returnHref=back?`${back}${back.includes("?")?"&":"?"}proposalVersion=${encodeURIComponent(data.id)}&sellSession=${encodeURIComponent(data.sellSessionId)}`:null;
 return <main className="min-h-screen bg-stone-950 p-5 text-white lg:p-10"><div className="mx-auto max-w-6xl"><header className="flex flex-col gap-5 border-b border-white/10 pb-6 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">COSMOS BLACK SEA · SALES</p><p className="mt-2 text-sm text-stone-400">Финальный этап продажи</p></div>{returnHref&&<a className="rounded-xl border border-white/15 px-4 py-3 text-sm text-amber-100" href={returnHref}>← Вернуться к продаже</a>}</header>{(liveCheck.priceChanged||liveCheck.statusChanged)&&<div className="mt-5 rounded-xl border border-amber-300/30 p-4 text-amber-100">Данные лота изменились после создания КП. В документе сохранены значения на момент создания.</div>}<section className="py-10"><p className="eyebrow">✓ Предложение готово</p><h1 className="mt-3 font-serif text-5xl">Номер {unit.unitNumber}</h1><p className="mt-3 text-stone-400">{unit.floor} этаж · {unit.area??"—"} м² · {formatRubles(unit.price)}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="panel p-5"><p className="text-xs text-stone-500">Условия покупки</p><strong className="mt-2 block">{purchase}</strong></div><div className="panel p-5"><p className="text-xs text-stone-500">Инвестиционный прогноз</p><strong className="mt-2 block">{investment?"Добавлен":"Не добавлен"}</strong></div></div></section>{investment&&<section className="panel mb-5 p-6"><p className="eyebrow">Инвестиционный прогноз</p><dl className="mt-3 grid gap-3 sm:grid-cols-3">{metrics.map(([label,content])=><div key={label}><dt className="text-stone-500">{label}</dt><dd>{content}</dd></div>)}</dl></section>}<div className="max-w-sm"><ProposalPreview importedProposalData={proposal} actionLabel="Открыть и скачать PDF"/></div></div></main>;
}
export function ImportedProposalVersion({contextId}:{contextId:string}){return <ProposalProvider><Content contextId={contextId}/></ProposalProvider>}
